In [1]:
kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]

In [2]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [3]:
weights = [w1, w2, w3]

In [7]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [10]:
crop_yield(kanto, weights)

56.8

In [11]:
import numpy as np

In [18]:
kanto = np.array(kanto)
weights = np.array(weights)
(kanto*weights).sum()

56.8

In [19]:
np.dot(kanto, weights)

56.8

In [21]:
climate_data = np.array([kanto, johto, hoenn, sinnoh, unova])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [26]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [28]:
import urllib.request

urllib.request.urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv',
                          'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x2b29aff1130>)

In [33]:
climate_data = np.genfromtxt('climate.txt', delimiter=",", skip_header = 1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [35]:
yields = climate_data @ weights
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [39]:
climate_results = np.concatenate(climate_data)

(10000, 3)

In [40]:
import os
os.getcwd()

'C:\\Users\\Fernando\\Documents\\MRes Biomedical Research\\Project 2\\Investigation\\LRCN drug prediction\\LRCN-drug-resistance'

In [43]:
os.makedirs('./data', exist_ok = True)

In [44]:
url1 = 'https://hub.jovian.ml/wp-content/uploads/2020/08/loans1.txt'
url2 = 'https://hub.jovian.ml/wp-content/uploads/2020/08/loans2.txt'
url3 = 'https://hub.jovian.ml/wp-content/uploads/2020/08/loans3.txt'

In [46]:
import urllib.request
urllib.request.urlretrieve(url1, './data/loans1.txt')
urllib.request.urlretrieve(url2, './data/loans2.txt')
urllib.request.urlretrieve(url3, './data/loans3.txt')

('./data/loans3.txt', <http.client.HTTPMessage at 0x2b29df95760>)

In [51]:
file1 = open("./data/loans1.txt", mode = 'r')
file1_contents = file1.read()
print(file1_contents)

amount,duration,rate,down_payment
100000,36,0.08,20000
200000,12,0.1,
628400,120,0.12,100000
4637400,240,0.06,
42900,90,0.07,8900
916000,16,0.13,
45230,48,0.08,4300
991360,99,0.08,
423000,27,0.09,47200


In [52]:
import pandas as pd

In [53]:
pd.read_csv("./data/loans1.txt")

amount  duration  rate  down_payment
0   100000        36  0.08       20000.0
1   200000        12  0.10           NaN
2   628400       120  0.12      100000.0
3  4637400       240  0.06           NaN
4    42900        90  0.07        8900.0
5   916000        16  0.13           NaN
6    45230        48  0.08        4300.0
7   991360        99  0.08           NaN
8   423000        27  0.09       47200.0